// benchmarks/jfb-ticker/frameworks/react/src/main.tsx
// React implementation of the jfb-ticker benchmark. Uses useReducer at
// the top level for state, flushSync to force synchronous commits per
// iteration (so the loop semantics match LLui's per-tick flush), and
// React.memo on Row so unchanged rows skip re-rendering on partial
// updates. Without memo, React re-renders every row on any state
// change, which is the unoptimised baseline; with memo, this is what
// a competent React developer would ship.

import { memo, useReducer, useRef } from 'react'
import { createRoot } from 'react-dom/client'
import { flushSync } from 'react-dom'
import { initialState, initialDashboard } from '../../../shared/data.js'
import {
  generateTick,
  generateNarrowTick,
  generateChurn,
  nextDisplayMode,
} from '../../../shared/operations.js'
import { mulberry32, SEED } from '../../../shared/prng.js'
import type {
  Dashboard,
  DisplayMode,
  Symbol as SymbolRow,
  TickerState,
} from '../../../shared/types.js'

type OpKind = 'mount' | 'tick' | 'narrow' | 'toggle' | 'churn' | 'clear'

type RngBox = {
  rng: () => number
  nextSymbolId: number
}

function reducer(state: TickerState, action: { kind: OpKind; box: RngBox }): TickerState {
  const { kind, box } = action
  switch (kind) {
    case 'mount':
      box.rng = mulberry32(SEED)
      box.nextSymbolId = 201
      return initialState()
    case 'tick': {
      const tick = generateTick(
        box.rng,
        state.symbols.length,
        state.dashboard.tickCount,
        state.symbols,
      )
      const dashboard = { ...state.dashboard, ...tick.dashboardUpdates }
      const symbols = state.symbols.slice()
      for (const patch of tick.symbolUpdates) {
        const prev = symbols[patch.index]
        if (!prev) continue
        symbols[patch.index] = {
          ...prev,
          price: patch.price,
          change: patch.change,
          changePct: patch.changePct,
          volume: patch.volume,
          lastTickAt: patch.lastTickAt,
        }
      }
      return { dashboard, symbols }
    }
    case 'narrow': {
      const tick = generateNarrowTick(box.rng, state.dashboard.tickCount)
      return { ...state, dashboard: { ...state.dashboard, ...tick.dashboardUpdates } }
    }
    case 'toggle':
      return {
        ...state,
        dashboard: {
          ...state.dashboard,
          displayMode: nextDisplayMode(state.dashboard.displayMode),
          tickCount: state.dashboard.tickCount + 1,
        },
      }
    case 'churn': {
      const { newSymbols, nextId } = generateChurn(box.rng, 50, box.nextSymbolId)
      box.nextSymbolId = nextId
      return {
        dashboard: { ...state.dashboard, tickCount: state.dashboard.tickCount + 1 },
        symbols: [...state.symbols.slice(50), ...newSymbols],
      }
    }
    case 'clear':
      return {
        dashboard: { ...initialDashboard(), tickCount: state.dashboard.tickCount + 1 },
        symbols: [],
      }
  }
}

type RowProps = { sym: SymbolRow; mode: DisplayMode }

const Row = memo(
  function Row({ sym, mode }: RowProps) {
    return (
      <tr className={`mode-${mode}`}>
        <td>{sym.ticker}</td>
        <td className="col-price">{sym.price.toFixed(2)}</td>
        <td className="col-change">{sym.change.toFixed(2)}</td>
        <td className="col-change">{sym.changePct.toFixed(2)}</td>
        <td className="col-volume">{sym.volume}</td>
        <td>{sym.lastTickAt}</td>
      </tr>
    )
  },
  (prev, next) => prev.sym === next.sym && prev.mode === next.mode,
)

function Cell({ k, v, id }: { k: string; v: string | number; id?: string }) {
  return (
    <div className="ticker-cell">
      <span className="k">{k}</span>
      <span className="v" id={id}>
        {v}
      </span>
    </div>
  )
}

function App() {
  const [state, dispatch] = useReducer(reducer, undefined, initialState)
  const boxRef = useRef<RngBox>({ rng: mulberry32(SEED), nextSymbolId: 201 })

  function op(kind: OpKind, iters: number): void {
    for (let i = 0; i < iters; i++) {
      flushSync(() => dispatch({ kind, box: boxRef.current }))
    }
  }

  const d: Dashboard = state.dashboard
  return (
    <div id="ticker">
      <h1>React ticker</h1>

      <div className="ticker-grid">
        <Cell k="Index" v={d.indexValue.toFixed(2)} />
        <Cell k="Δ" v={d.indexChange.toFixed(2)} />
        <Cell k="Δ%" v={d.indexChangePct.toFixed(2)} />
        <Cell k="Tick" v={d.lastTick} />
        <Cell k="Adv" v={d.advancers} />
        <Cell k="Dec" v={d.decliners} />
        <Cell k="Unch" v={d.unchanged} />
        <Cell k="NH" v={d.newHighs} />
        <Cell k="Tech" v={d.sectorTech.toFixed(2)} />
        <Cell k="Fin" v={d.sectorFin.toFixed(2)} />
        <Cell k="Health" v={d.sectorHealth.toFixed(2)} />
        <Cell k="Energy" v={d.sectorEnergy.toFixed(2)} />
        <Cell k="Cons" v={d.sectorConsumer.toFixed(2)} />
        <Cell k="Ind" v={d.sectorIndustrial.toFixed(2)} />
        <Cell k="Util" v={d.sectorUtilities.toFixed(2)} />
        <Cell k="Mat" v={d.sectorMaterials.toFixed(2)} />
        <Cell k="RE" v={d.sectorRealestate.toFixed(2)} />
        <Cell k="Comm" v={d.sectorComm.toFixed(2)} />
        <Cell k="Stap" v={d.sectorStaples.toFixed(2)} />
        <Cell k="EUR" v={d.usdEur.toFixed(4)} />
        <Cell k="JPY" v={d.usdJpy.toFixed(2)} />
        <Cell k="GBP" v={d.usdGbp.toFixed(4)} />
        <Cell k="CNY" v={d.usdCny.toFixed(4)} />
        <Cell k="Oil" v={d.oil.toFixed(2)} />
        <Cell k="Gold" v={d.gold.toFixed(2)} />
        <Cell k="Slv" v={d.silver.toFixed(2)} />
        <Cell k="Cu" v={d.copper.toFixed(2)} />
        <Cell k="Mode" v={d.displayMode} />
        <Cell k="#" v={d.tickCount} id="ticker-counter" />
        <Cell k="Mkt" v={d.marketState} />
        <Cell k="Lat" v={d.latencyMs} />
        <Cell k="Feeds" v={d.connectedFeeds} />
      </div>

      <div className="controls">
        <button id="mount" type="button" className="btn" onClick={() => op('mount', 1)}>
          Mount 200
        </button>
        <button id="tick-1" type="button" className="btn" onClick={() => op('tick', 1)}>
          1 tick
        </button>
        <button id="tick-100" type="button" className="btn" onClick={() => op('tick', 100)}>
          100 ticks
        </button>
        <button id="burst-1k" type="button" className="btn" onClick={() => op('tick', 1000)}>
          Burst 1k
        </button>
        <button id="narrow-100" type="button" className="btn" onClick={() => op('narrow', 100)}>
          100 narrow
        </button>
        <button id="wide-toggle" type="button" className="btn" onClick={() => op('toggle', 1)}>
          Toggle mode
        </button>
        <button id="churn-50" type="button" className="btn" onClick={() => op('churn', 1)}>
          Churn 50
        </button>
        <button id="clear" type="button" className="btn" onClick={() => op('clear', 1)}>
          Clear
        </button>
      </div>

      <table id="symbols" className="ticker">
        <tbody>
          {state.symbols.map((sym) => (
            <Row key={sym.id} sym={sym} mode={d.displayMode} />
          ))}
        </tbody>
      </table>
    </div>
  )
}

createRoot(document.getElementById('main')!).render(<App />)

// benchmarks/jfb-ticker/frameworks/solid/src/main.tsx
// Solid implementation of the jfb-ticker benchmark. Uses createStore +
// produce() for fine-grained reactivity. Each setStore call propagates
// synchronously, so 100 calls in a row produce 100 commits — matching
// the LLui send+flush loop semantics.

import { render } from 'solid-js/web'
import { createStore, produce } from 'solid-js/store'
import { For } from 'solid-js'
import { initialState, initialDashboard } from '../../../shared/data.js'
import {
  generateTick,
  generateNarrowTick,
  generateChurn,
  nextDisplayMode,
} from '../../../shared/operations.js'
import { mulberry32, SEED } from '../../../shared/prng.js'
import type { TickerState } from '../../../shared/types.js'

let rng = mulberry32(SEED)
let nextSymbolId = 201

const [state, setState] = createStore<TickerState>(initialState())

type OpKind = 'mount' | 'tick' | 'narrow' | 'toggle' | 'churn' | 'clear'

function op(kind: OpKind, iters: number): void {
  for (let i = 0; i < iters; i++) applyOnce(kind)
}

function applyOnce(kind: OpKind): void {
  switch (kind) {
    case 'mount': {
      rng = mulberry32(SEED)
      nextSymbolId = 201
      setState(initialState())
      return
    }
    case 'tick': {
      const tick = generateTick(rng, state.symbols.length, state.dashboard.tickCount, state.symbols)
      setState(
        produce((s: TickerState) => {
          Object.assign(s.dashboard, tick.dashboardUpdates)
          for (const patch of tick.symbolUpdates) {
            const sym = s.symbols[patch.index]
            if (!sym) continue
            sym.price = patch.price
            sym.change = patch.change
            sym.changePct = patch.changePct
            sym.volume = patch.volume
            sym.lastTickAt = patch.lastTickAt
          }
        }),
      )
      return
    }
    case 'narrow': {
      const tick = generateNarrowTick(rng, state.dashboard.tickCount)
      setState(
        produce((s: TickerState) => {
          Object.assign(s.dashboard, tick.dashboardUpdates)
        }),
      )
      return
    }
    case 'toggle': {
      setState(
        produce((s: TickerState) => {
          s.dashboard.displayMode = nextDisplayMode(s.dashboard.displayMode)
          s.dashboard.tickCount += 1
        }),
      )
      return
    }
    case 'churn': {
      const { newSymbols, nextId } = generateChurn(rng, 50, nextSymbolId)
      nextSymbolId = nextId
      setState(
        produce((s: TickerState) => {
          s.symbols.splice(0, 50)
          s.symbols.push(...newSymbols)
          s.dashboard.tickCount += 1
        }),
      )
      return
    }
    case 'clear': {
      setState(
        produce((s: TickerState) => {
          const next = s.dashboard.tickCount + 1
          s.symbols = []
          s.dashboard = { ...initialDashboard(), tickCount: next }
        }),
      )
      return
    }
  }
}

function App() {
  return (
    <div id="ticker">
      <h1>Solid ticker</h1>

      <div class="ticker-grid">
        <div class="ticker-cell">
          <span class="k">Index</span>
          <span class="v">{state.dashboard.indexValue.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Δ</span>
          <span class="v">{state.dashboard.indexChange.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Δ%</span>
          <span class="v">{state.dashboard.indexChangePct.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Tick</span>
          <span class="v">{state.dashboard.lastTick}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Adv</span>
          <span class="v">{state.dashboard.advancers}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Dec</span>
          <span class="v">{state.dashboard.decliners}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Unch</span>
          <span class="v">{state.dashboard.unchanged}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">NH</span>
          <span class="v">{state.dashboard.newHighs}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Tech</span>
          <span class="v">{state.dashboard.sectorTech.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Fin</span>
          <span class="v">{state.dashboard.sectorFin.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Health</span>
          <span class="v">{state.dashboard.sectorHealth.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Energy</span>
          <span class="v">{state.dashboard.sectorEnergy.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Cons</span>
          <span class="v">{state.dashboard.sectorConsumer.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Ind</span>
          <span class="v">{state.dashboard.sectorIndustrial.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Util</span>
          <span class="v">{state.dashboard.sectorUtilities.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Mat</span>
          <span class="v">{state.dashboard.sectorMaterials.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">RE</span>
          <span class="v">{state.dashboard.sectorRealestate.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Comm</span>
          <span class="v">{state.dashboard.sectorComm.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Stap</span>
          <span class="v">{state.dashboard.sectorStaples.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">EUR</span>
          <span class="v">{state.dashboard.usdEur.toFixed(4)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">JPY</span>
          <span class="v">{state.dashboard.usdJpy.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">GBP</span>
          <span class="v">{state.dashboard.usdGbp.toFixed(4)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">CNY</span>
          <span class="v">{state.dashboard.usdCny.toFixed(4)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Oil</span>
          <span class="v">{state.dashboard.oil.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Gold</span>
          <span class="v">{state.dashboard.gold.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Slv</span>
          <span class="v">{state.dashboard.silver.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Cu</span>
          <span class="v">{state.dashboard.copper.toFixed(2)}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Mode</span>
          <span class="v">{state.dashboard.displayMode}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">#</span>
          <span class="v" id="ticker-counter">
            {state.dashboard.tickCount}
          </span>
        </div>
        <div class="ticker-cell">
          <span class="k">Mkt</span>
          <span class="v">{state.dashboard.marketState}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Lat</span>
          <span class="v">{state.dashboard.latencyMs}</span>
        </div>
        <div class="ticker-cell">
          <span class="k">Feeds</span>
          <span class="v">{state.dashboard.connectedFeeds}</span>
        </div>
      </div>

      <div class="controls">
        <button id="mount" type="button" class="btn" onClick={() => op('mount', 1)}>
          Mount 200
        </button>
        <button id="tick-1" type="button" class="btn" onClick={() => op('tick', 1)}>
          1 tick
        </button>
        <button id="tick-100" type="button" class="btn" onClick={() => op('tick', 100)}>
          100 ticks
        </button>
        <button id="burst-1k" type="button" class="btn" onClick={() => op('tick', 1000)}>
          Burst 1k
        </button>
        <button id="narrow-100" type="button" class="btn" onClick={() => op('narrow', 100)}>
          100 narrow
        </button>
        <button id="wide-toggle" type="button" class="btn" onClick={() => op('toggle', 1)}>
          Toggle mode
        </button>
        <button id="churn-50" type="button" class="btn" onClick={() => op('churn', 1)}>
          Churn 50
        </button>
        <button id="clear" type="button" class="btn" onClick={() => op('clear', 1)}>
          Clear
        </button>
      </div>

      <table id="symbols" class="ticker">
        <tbody>
          <For each={state.symbols}>
            {(sym) => (
              <tr class={`mode-${state.dashboard.displayMode}`}>
                <td>{sym.ticker}</td>
                <td class="col-price">{sym.price.toFixed(2)}</td>
                <td class="col-change">{sym.change.toFixed(2)}</td>
                <td class="col-change">{sym.changePct.toFixed(2)}</td>
                <td class="col-volume">{sym.volume}</td>
                <td>{sym.lastTickAt}</td>
              </tr>
            )}
          </For>
        </tbody>
      </table>
    </div>
  )
}

render(() => <App />, document.getElementById('main')!)
